// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFayCZhCAH6KlFYKACCnEU3EUu3m9kBE',
    appId: '1:762967530894:web:201de2d9ddac34787b98df',
    messagingSenderId: '762967530894',
    projectId: 'solar-dryer-iot',
    authDomain: 'solar-dryer-iot.firebaseapp.com',
    databaseURL: 'https://solar-dryer-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-dryer-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Md17-ZOkO0VMVyJRwvditlSbPEjgfa8',
    appId: '1:762967530894:android:07e349d36e552e1f7b98df',
    messagingSenderId: '762967530894',
    projectId: 'solar-dryer-iot',
    databaseURL: 'https://solar-dryer-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-dryer-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SxBSJnkgksAGJhrHkSHQ5Ysnkh6ACkk',
    appId: '1:762967530894:ios:d4243e071c4edf447b98df',
    messagingSenderId: '762967530894',
    projectId: 'solar-dryer-iot',
    databaseURL: 'https://solar-dryer-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-dryer-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7SxBSJnkgksAGJhrHkSHQ5Ysnkh6ACkk',
    appId: '1:762967530894:ios:d4243e071c4edf447b98df',
    messagingSenderId: '762967530894',
    projectId: 'solar-dryer-iot',
    databaseURL: 'https://solar-dryer-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-dryer-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiFayCZhCAH6KlFYKACCnEU3EUu3m9kBE',
    appId: '1:762967530894:web:95e7e79b21bedf2e7b98df',
    messagingSenderId: '762967530894',
    projectId: 'solar-dryer-iot',
    authDomain: 'solar-dryer-iot.firebaseapp.com',
    databaseURL: 'https://solar-dryer-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-dryer-iot.firebasestorage.app',
  );

}